<a href="https://colab.research.google.com/github/amithpaul/GlassSVM/blob/main/GlassSVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

glassdata=pd.read_csv("/content/drive/MyDrive/glass.csv")

In [4]:
glassdata.head() #shows first 5 records

RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  Type
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

## Pre-Processing

In [5]:
glassdata.describe() #gives aggregate function and other details results for each feature

RI          Na          Mg          Al          Si           K  \
count  214.000000  214.000000  214.000000  214.000000  214.000000  214.000000   
mean     1.518365   13.407850    2.684533    1.444907   72.650935    0.497056   
std      0.003037    0.816604    1.442408    0.499270    0.774546    0.652192   
min      1.511150   10.730000    0.000000    0.290000   69.810000    0.000000   
25%      1.516522   12.907500    2.115000    1.190000   72.280000    0.122500   
50%      1.517680   13.300000    3.480000    1.360000   72.790000    0.555000   
75%      1.519157   13.825000    3.600000    1.630000   73.087500    0.610000   
max      1.533930   17.380000    4.490000    3.500000   75.410000    6.210000   

               Ca          Ba          Fe        Type  
count  214.000000  214.000000  214.000000  214.000000  
mean     8.956963    0.175047    0.057009    2.780374  
std      1.423153    0.497219    0.097439    2.103739  
min      5.430000    0.000000    0.000000    1.000000  
25%      8.240000    0.000000    0.000000    1.000000  
50%      8.600000    0.000000    0.000000    2.000000  
75%      9.172500    0.000000    0.100000    3.000000  
max     16.190000    3.150000    0.510000    7.000000

From the description we can say that Ba and Fe can be exclued as most of the values (75% row of result from descibe functiion) for these fields are zero and are thus irrelevant as a costituent of glass.

In [6]:
print((glassdata['Ba']==0).sum()/len(glassdata))
print((glassdata['Fe']==0).sum()/len(glassdata))

0.822429906542056
0.6728971962616822


In [7]:
# Deletes the irrelevant features
glassdata.drop('Ba',axis=1,inplace=True)
glassdata.drop('Fe',axis=1,inplace=True)

In [9]:
# Print altered dataset
print(glassdata)

          RI     Na    Mg    Al     Si     K    Ca  Type
0    1.52101  13.64  4.49  1.10  71.78  0.06  8.75     1
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83     1
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78     1
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22     1
4    1.51742  13.27  3.62  1.24  73.08  0.55  8.07     1
..       ...    ...   ...   ...    ...   ...   ...   ...
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18     7
210  1.51685  14.92  0.00  1.99  73.06  0.00  8.40     7
211  1.52065  14.36  0.00  2.02  73.42  0.00  8.44     7
212  1.51651  14.38  0.00  1.94  73.61  0.00  8.48     7
213  1.51711  14.23  0.00  2.08  73.36  0.00  8.62     7

[214 rows x 8 columns]


In [12]:
from sklearn.model_selection import train_test_split

X = glassdata.iloc[:,:-1] # Takes all columns except the last column
Y = glassdata.iloc[:,-1] # Takes only the last column (Type)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# print(X_train.shape)
# print(X_test.shape)
# print(Y_train.shape)
# print(Y_test.shape)

(171, 7)
(43, 7)
(171,)
(43,)


## Training

In [14]:
from sklearn.svm import SVC

model = SVC(kernel='linear',C=0.8)
model.fit(X_train, Y_train)

Y_predict=model.predict(X_test)

### Metrics

#### Accuracy score

In [15]:
from sklearn.metrics import accuracy_score

print(accuracy_score(Y_test,Y_predict))

0.6744186046511628


#### Confusion Matrix

In [16]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(Y_test,Y_predict))

[[10  1  0  0  0  0]
 [ 4  9  0  0  0  1]
 [ 1  2  0  0  0  0]
 [ 0  2  0  2  0  0]
 [ 0  1  0  1  1  0]
 [ 0  1  0  0  0  7]]


#### Classification Report

In [17]:
from sklearn.metrics import classification_report

print(classification_report(Y_test,Y_predict))

              precision    recall  f1-score   support

           1       0.67      0.91      0.77        11
           2       0.56      0.64      0.60        14
           3       0.00      0.00      0.00         3
           5       0.67      0.50      0.57         4
           6       1.00      0.33      0.50         3
           7       0.88      0.88      0.88         8

    accuracy                           0.67        43
   macro avg       0.63      0.54      0.55        43
weighted avg       0.65      0.67      0.64        43

